### ISSUE TITLE
Example for AT command

### ISSUE THREAD

**Issue by MathiasKoch** [thejpster/embedded_serial#1]
Hi.

Do you have any resources, or complete examples where these traits are being used for AT command based communication, in a complete fashion? preferably in a non-blocking way? 

I have a bit of trouble implementing a proper logic for handling AT communication with an AT modem, where the TX and RX parts sort of have to interconnect.. Eg. send a command and wait for response (possibly multiple responses), while still keeping the option of event driven responses (client connected, disconnected, connection lost, etc.) 

And was wondering if you could provide some guidance on a best practice for this? 

Preferably i would like to use some sort of async/await/futures based approach, with a tasking layer like RTFM? I just keep feeling like I'm approaching this in a very C-typical blocking way.

Thank you.

**Comment by thejpster** [comment]
I'm afraid I don't use this crate any more - the recommendation is to use the working groups `embedded-hal` crate (https://crates.io/crates/embedded-hal).

I have use embedded-hal to talk to an AT modem. The API has a non-blocking mode, so you can spin in a loop polling multiple serial ports. If your serial driver raises in Interrupt on data RX, you can even sleep with `wfi` when there's nothing left to poll. Using Futures for this I believe is on the roadmap, but IIRC there are issues preventing it working on stable at the moment. https://github.com/japaric/no-std-async-experiments-2 is probably useful further reading.
